import type { Insight } from './insights';

// Second publishing batch: practical follow-ups to the core authority articles.
export const dayTwoInsights: Insight[] = [
  {
    slug: 'property-media-operations-dashboard', category: 'Operations',
    title: 'What should a real estate photography operations dashboard show?',
    description: 'Choose dashboard signals that expose today’s shoots, blocked handoffs, revisions and deliveries without hiding the next owner.',
    answer: 'Show today’s shoots, jobs awaiting source files, editing and review queues, blocked or unowned work, revisions and deliveries due soon. Each item should open to the property job with its next action, owner and due time. Count exceptions by stage, but do not let summary totals replace the underlying service-level detail.',
    intro: 'A dashboard is useful when it helps a coordinator decide what needs attention now. Attractive totals cannot answer why a specific floor plan is late.',
    image: '/images/reference/in-studio.webp', imageAlt: 'Property media team coordinating operations', readingMinutes: 5,
    sections: [
      { heading: 'Start with decisions, then choose the signals', paragraphs: ['Ask what the coordinator checks each morning: which appointments need access confirmation, which uploads are missing, which editor submissions await review, and which promises may miss delivery. Group these into actionable views rather than one large activity feed.', 'Each card should link to the job and show an accountable next owner. A count of blocked jobs is only useful if the team can see the reason and action.'], bullets: ['Today: confirmed shoots and access exceptions.', 'Production: missing source sets and overdue editor work.', 'Review: submissions, revisions and unapproved deliverables.', 'Delivery: due packages and client-view checks.'] },
      { heading: 'Preserve service-level truth', paragraphs: ['A multi-service order can have approved photos and unfinished video. A top-line job badge must not call the entire package complete. Show the job stage and the dispositions of its ordered services, with a distinct signal for explicitly agreed partial delivery.'] },
      { heading: 'Illustrative morning review', paragraphs: ['In a fictional studio, the board lists two shoots today with missing access notes, three editor submissions awaiting human review and one due-today order with an unapproved floor plan. The coordinator assigns owners and decision times to those four exceptions before checking routine work. The example illustrates a dashboard decision, not a measured result.'] },
      { heading: 'Keep the dashboard maintainable', paragraphs: ['Define the source of each signal and the person who updates it. If a number is routinely stale, fix the handoff rule or remove the metric. Start with a small exception view and add a measure only when a real decision depends on it.'], bullets: ['Can a user click through to the current job record?', 'Is “late” measured against a real due time and local time zone?', 'Does the dashboard distinguish submitted from approved?'] },
    ],
    closing: 'A good operations dashboard is an entry point to accountable actions, not a wall of totals.',
    related: [{ href: '/insights/track-every-active-property-media-job', label: 'Define the underlying job record' }, { href: '/real-estate-media-production-management', label: 'See the planned production view' }],
  },
  {
    slug: 'real-estate-photography-operations-checklist', category: 'Operations',
    title: 'Real estate photography operations checklist for a busy week',
    description: 'A reusable daily and weekly checklist for scheduling, production handoffs, human review and client delivery.',
    answer: 'Each day, verify upcoming access and assignments, inspect missing files and unowned editing, clear review and revision queues, then check delivery commitments. Each week, review repeated blockers, capacity and unclear handoffs. Record the next owner and due time on the job while making each decision.',
    intro: 'A checklist should reduce forgotten handoffs without making the owner inspect every routine task. Adapt this sequence to the services, deadlines and roles in your studio.',
    image: '/images/reference/on-site.webp', imageAlt: 'Photographer preparing a real estate media shoot', readingMinutes: 5,
    sections: [
      { heading: 'Before the shooting day', paragraphs: ['Confirm the next appointments, property addresses, access contacts, ordered services and photographer acknowledgements. Check travel and specialty coverage. An unconfirmed detail gets an owner and a time to resolve it, not a silent assumption.'], bullets: ['Match each appointment to the current job brief.', 'Resolve missing access before the photographer travels.', 'Check whether new rush work fits production as well as the calendar.'] },
      { heading: 'During production', paragraphs: ['Match incoming source sets to the correct property and service. Assign the editor with complete instructions and an expected submission time. Review blocked work and overdue handoffs before they become client surprises. Keep corrected versions separate from superseded files.'], bullets: ['Find shoots with no file result.', 'Find editing jobs with missing source sets or no owner.', 'Find submitted finals waiting for a reviewer.'] },
      { heading: 'Before delivery', paragraphs: ['Compare the proposed package with the ordered services and recorded approvals. Open it from the recipient perspective, confirm access and property identity, and record the handoff. If a service is outstanding, obtain an explicit partial-delivery agreement and name the remaining owner.'] },
      { heading: 'Weekly improvement example', paragraphs: ['Suppose three fictional jobs needed a last-minute call for access instructions. The weekly review traces the cause to a request form that never asks for a site contact. The studio updates intake, then watches whether next week’s access exceptions fall. This is an illustrative process, not a claimed outcome.', 'Keep this checklist near the active-job board and remove checks that duplicate an automated or reliably owned step.'], bullets: ['Which blocker repeated?', 'Which role lacked a clear decision rule?', 'Which client promise needs a more realistic capacity check?'] },
    ],
    closing: 'Use the checklist to create decisions at the right time, then improve the rule behind recurring exceptions.',
    related: [{ href: '/resources/shoot-to-delivery-checklist', label: 'Use the job-level checklist' }, { href: '/insights/property-media-job-triage', label: 'Run daily exception triage' }],
  },
  {
    slug: 'find-stuck-property-media-jobs', category: 'Operations',
    title: 'How to find stuck property-media jobs before clients ask',
    description: 'Define stalled work with expected handoff times, missing inputs and owners, then create an exception queue for early action.',
    answer: 'Set an expected next action and time at every handoff. Flag a job when that time passes, an ordered service has missing inputs, a submission waits for review, or no one owns the next decision. Investigate those exceptions daily and update the client commitment if the delay changes it.',
    intro: 'A job can be stuck without being late yet. The useful warning is a missed internal handoff that threatens the promised client delivery.',
    image: '/images/reference/interior-2.webp', imageAlt: 'Property interior representing a pending media order', readingMinutes: 5,
    sections: [
      { heading: 'Define a stall for each stage', paragraphs: ['A scheduled shoot stalls if access remains unconfirmed near the appointment. A captured job stalls if sources have not arrived by the agreed upload time. Editing stalls when assigned work passes its check-in or submission time. Review stalls when a submitted version has no decision. These are operational thresholds the team sets, not universal industry deadlines.'] },
      { heading: 'Create an exception queue with enough context', paragraphs: ['For each flagged job, show property, ordered services, current owner, expected action, target time, reason and who can unblock it. Sort by client commitment and downstream dependency. Do not simply send the owner an alert with no next step.'], bullets: ['Missing input: ask the person who can provide it.', 'Unowned: assign a decision maker now.', 'Overdue: confirm a revised internal time and delivery impact.', 'Rejected: link the exact requested change to the correct version.'] },
      { heading: 'Illustrative early catch', paragraphs: ['A fictional floor-plan draft is due for review by noon and client delivery is tomorrow morning. At 12:30 it still has no reviewer. The production lead assigns one and verifies the draft exists. If a correction cannot fit the remaining window, the coordinator tells the client what can be delivered and when. The intervention begins before the client needs to chase.'] },
      { heading: 'Improve the signal over time', paragraphs: ['Review false alarms and repeated misses weekly. A cutoff that never reflects service complexity causes noise; one that fires after client delivery is too late. Use actual team commitments and keep the job record current at every handoff.'] },
    ],
    closing: 'Detect the missing next action early enough that someone can still change the outcome.',
    related: [{ href: '/insights/property-media-job-triage', label: 'Prioritize the flagged jobs' }, { href: '/resources/property-job-status-board-template', label: 'Use a status board' }],
  },
  {
    slug: 'in-house-versus-outsourced-property-photo-editing', category: 'Editing',
    title: 'In-house versus outsourced real estate photo editing: an operations guide',
    description: 'Compare editing models by brief quality, capacity, review ownership, revision handling and resilience rather than assuming a universal winner.',
    answer: 'Choose an editing model based on the work your team can brief, review and deliver reliably. In-house editing offers direct collaboration but requires staffing and coverage; outsourcing may add flexible capacity but requires explicit file handoffs, standards and revision ownership. Test both against the same representative property job.',
    intro: 'The editor’s location does not remove the need for a complete brief or human QC. A studio should compare the whole operating workflow, not just the quoted edit cost.',
    image: '/images/reference/in-studio.webp', imageAlt: 'Property media editor at work', readingMinutes: 6,
    sections: [
      { heading: 'Compare the real coordination work', paragraphs: ['Map source intake, editing assignment, style instructions, turnaround commitments, reviewer availability and corrections. For a local team, ask who covers leave and busy periods. For an external editor, ask how missing files, unclear instructions and time-zone handoffs are handled.'], table: { headers: ['Decision', 'In-house question', 'Outsourced question'], rows: [['Capacity', 'Who covers peaks and absences?', 'How is peak capacity confirmed?'], ['Brief', 'Where are job exceptions recorded?', 'Can the editor act without a separate chat?'], ['Review', 'Who approves finals independently?', 'Who checks the returned version?'], ['Revision', 'How is priority decided?', 'How are requests and versions traced?']] } },
      { heading: 'Test one representative job', paragraphs: ['Use a fictional multi-service property with special editing instructions and one correction. Time the handoffs and count the decisions that need another person’s memory. Compare whether both models deliver a complete, approved package under your own client promise. Do not treat a fast first submission as a complete handoff.'] },
      { heading: 'Allow a mixed model where useful', paragraphs: ['Some teams keep specialty or urgent edits in-house while using external capacity for standardized work. If you do, assign one production owner for the property and one reviewer for each output. The client should not have to understand your staffing model to know what will be delivered.'], bullets: ['Document the acceptance criteria before delegating.', 'Keep styles and property-specific exceptions distinct.', 'Retain a backup route for unavailable editors.', 'Measure rework and missed handoffs, not only first-pass turnaround.'] },
      { heading: 'Decide with your actual constraints', paragraphs: ['Record cost, staffing, quality review effort, communication windows and delivery reliability from your own trial. Avoid broad claims that one model always scales better. Revisit the decision as service mix and team capacity change.'] },
    ],
    closing: 'The right model is the one your team can operate and review consistently for its actual mix of jobs.',
    related: [{ href: '/insights/manage-multiple-real-estate-photo-editors', label: 'Manage editor assignments' }, { href: '/resources/media-editing-review-checklist', label: 'Use the review checklist' }],
  },
  {
    slug: 'write-property-photo-editing-instructions', category: 'Editing',
    title: 'How to write real estate photo editing instructions editors can act on',
    description: 'Turn vague property-photo editing requests into a usable brief with sources, references, exceptions, outputs and review criteria.',
    answer: 'Write one brief that identifies the property, source files, ordered outputs, standard style reference, specific exceptions, deadline and reviewer. For every special request, name the affected image or area and the intended result. Ask the editor to flag ambiguity before changing property details.',
    intro: '“Make it look good” delegates an aesthetic guess. The most useful editing instructions separate the studio’s reusable standard from the few property-specific decisions that matter today.',
    image: '/images/reference/interior.webp', imageAlt: 'Residential interior representing an editing assignment', readingMinutes: 5,
    sections: [
      { heading: 'Start with context and expected outputs', paragraphs: ['Include job identifier, address label, ordered service, source location, selected image set, target format and due time with time zone. Link to the current style guide rather than pasting contradictory directions into every assignment. State who will review the submission.'] },
      { heading: 'Make exceptions specific and bounded', paragraphs: ['Describe which image or room needs attention and what change is expected. For example, “on kitchen image 08, keep window detail while matching the approved reference exposure” gives more direction than “fix the windows.” If a request would alter an important property feature, pause and seek an explicit client or reviewer decision instead of assuming.'], bullets: ['Reference the file or frame.', 'Describe the acceptable outcome.', 'State what should not change.', 'Identify the person who can answer questions.'] },
      { heading: 'Illustrative brief excerpt', paragraphs: ['For a fictional three-bedroom listing: “Edit the selected interior and exterior source sets in folder JOB-184/source. Deliver approved-size JPEGs in JOB-184/submitted/v1 by 10 am local. Follow the current studio color reference. For living-room image 12, retain the window view; for exterior image 03, ask the reviewer before any object removal. Reply if a selected source is absent.” This example is a template, not a description of an actual customer.'] },
      { heading: 'Close the loop after submission', paragraphs: ['The reviewer checks the result against the brief and ordered output list. Requests for changes should cite the submitted version and affected files. Update the reusable style guide when the same clarification recurs across jobs; leave one-off exceptions on the job.'] },
    ],
    closing: 'Good instructions let an editor work independently without guessing what the client ordered or what the reviewer will accept.',
    related: [{ href: '/resources/photographer-handoff-template', label: 'Start with the photographer handoff' }, { href: '/insights/real-estate-photography-editing-workflow', label: 'Map the editing workflow' }],
  },
  {
    slug: 'property-media-editing-queue', category: 'Editing',
    title: 'How to build an editing queue for multiple properties',
    description: 'Prioritize property editing by promised delivery, service dependencies, complete inputs and editor capacity.',
    answer: 'Put each service’s editing assignment in a queue with property ID, complete input status, editor, expected output, due time and review owner. Prioritize work by the client commitment and downstream review time, then flag missing sources and overloaded editors separately. Reorder deliberately when rush work arrives.',
    intro: 'A folder sorted by upload time does not tell an editor which job matters next or whether its brief is complete. The queue is a decision tool for the production lead and editors.',
    image: '/images/reference/in-studio.webp', imageAlt: 'Editor managing property media work', readingMinutes: 5,
    sections: [
      { heading: 'Choose the unit of work', paragraphs: ['Track photo, video and other service edits under their property job rather than one undifferentiated order. A service enters the ready queue only when sources and instructions are sufficient to start. Missing inputs belong in an exception queue with an owner, not silently at the bottom of a task list.'] },
      { heading: 'Prioritize the full path to delivery', paragraphs: ['Work backward from the client commitment to allow time for editing, human QC, corrections and packaging. Check whether an urgent job blocks another specialist service or shares an editor. Keep the order visible when it changes, including the reason and decision maker.'], bullets: ['Ready inputs and an assigned editor.', 'Submission time that leaves review capacity.', 'Visible blockers and fallback ownership.', 'Explicit handling for a newly accepted rush order.'] },
      { heading: 'Illustrative queue decision', paragraphs: ['A fictional studio has an afternoon photo job due tomorrow, a morning video edit due in two days, and a floor plan due tomorrow whose source notes are missing. The ready photo job can start now; the floor-plan intake owner chases notes, and the video editor receives a confirmed slot. If the notes arrive late, the lead revisits both reviewer capacity and the client promise instead of merely moving a row.'] },
      { heading: 'Review capacity at predictable times', paragraphs: ['At the start and end of a shift, check assignments with no acknowledgement, submissions waiting for QC and corrected versions approaching the cutoff. Track recurring causes of queue reshuffling; improve intake if missing source files repeatedly consume editor time.'] },
    ],
    closing: 'A queue should make the next feasible assignment obvious and the blocked work impossible to overlook.',
    related: [{ href: '/insights/manage-multiple-real-estate-photo-editors', label: 'Manage multiple editors' }, { href: '/real-estate-media-production-management', label: 'See the planned production workspace' }],
  },
  {
    slug: 'who-owns-property-media-quality-control', category: 'Quality review',
    title: 'Who should own quality control in a property-media company?',
    description: 'Choose a named QC decision maker and separate editing submission, approval and client delivery responsibilities.',
    answer: 'Give each deliverable a named reviewer who can approve it or request a specific correction. The reviewer may be an owner, production lead or dedicated QC person, depending on workload, but responsibility must be explicit. Keep editor submission, QC approval and delivery as separate decisions with a backup when the reviewer is unavailable.',
    intro: 'A job can sit after editing because everyone assumes someone else will inspect it. A clear QC owner helps the team catch missing or incorrect media before the client package is sent.',
    image: '/images/reference/interior-2.webp', imageAlt: 'Interior image representing a property media quality check', readingMinutes: 5,
    sections: [
      { heading: 'Define what the reviewer accepts', paragraphs: ['The reviewer compares submitted finals with the ordered services, property identity, client instructions and applicable studio standards. They record approval or a file-specific correction. The delivery owner checks the client package and access after approval; these can be the same person on a small team, but the two decisions remain distinct.'] },
      { heading: 'Choose a workable role model', paragraphs: ['An owner may review early on but can become a queue bottleneck. An editor may self-check technical output yet a second set of eyes may still be needed for job completeness and client requirements. A dedicated reviewer adds capacity only if that person has the brief and authority to decide. Define when unusual scope or client exceptions escalate to the owner.'], bullets: ['Who reviews each media type?', 'What evidence is required for approval?', 'Who covers the reviewer’s absence?', 'Who resolves disagreement over a client request?'] },
      { heading: 'Illustrative ownership handoff', paragraphs: ['For a fictional photo-and-floor-plan job, a photo editor submits images and a floor-plan specialist submits a draft. The assigned reviewer approves the photos but requests a label correction on the plan. The coordinator does not mark the full job ready. After the corrected plan is approved, the delivery owner checks the package and sends it.'] },
      { heading: 'Inspect the queue, not just the output', paragraphs: ['Show submissions waiting for review, changes requested and approved items with due times. If QC regularly waits on one person, adjust coverage or review cutoffs before promising faster delivery. Review repeated failures to improve the source brief or standards.'] },
    ],
    closing: 'QC is an accountable approval decision, supported by a complete brief and visible fallback coverage.',
    related: [{ href: '/resources/media-editing-review-checklist', label: 'Use the review checklist' }, { href: '/insights/real-estate-media-delivery-readiness', label: 'Check whole-job readiness' }],
  },
  {
    slug: 'prevent-double-booked-photographers', category: 'Scheduling',
    title: 'How to prevent double bookings in a photography team',
    description: 'Use one authoritative schedule, realistic travel windows and a confirmation rule for property photography assignments.',
    answer: 'Treat one schedule as authoritative for each photographer. Before confirming, check the entire block: travel, preparation, on-site services and any required buffer. Reserve the assignment with the current property brief, reject conflicts, and update every affected appointment when a shoot moves.',
    intro: 'Two non-overlapping calendar start times can still conflict if a photographer must travel, cover an added service or wait for property access. Avoiding double bookings requires a shared rule for what a confirmed slot means.',
    image: '/images/reference/exterior.webp', imageAlt: 'Property exterior representing a scheduled photography appointment', readingMinutes: 5,
    sections: [
      { heading: 'Define the bookable interval', paragraphs: ['Estimate on-site duration from the property and ordered services, then add realistic preparation and travel. A photo-and-video appointment may need a different interval from photos alone. Confirm availability and service qualifications before offering the time to a client.'] },
      { heading: 'Choose an authoritative schedule', paragraphs: ['Decide which calendar or job record owns confirmed bookings. Tentative holds need an expiry and a visible status. If team members keep personal calendars, document how time off and confirmed work reach the authoritative view. A copied event is not automatically a reliable booking.'], bullets: ['Block the full interval, not only the arrival time.', 'Require a named assignee and acknowledgement.', 'Recheck conflicts after every reschedule or service change.', 'Record who confirmed the client and site contact.'] },
      { heading: 'Illustrative conflict check', paragraphs: ['A fictional photographer finishes a floor-plan and photo shoot at 11:30 am. The next property is listed at noon but travel and equipment reset require more time. The scheduler offers a later slot or another qualified photographer rather than treating the half-hour gap as available. If the first appointment changes, the second is revalidated before anyone promises the new plan.'] },
      { heading: 'Plan recovery for conflicts you still encounter', paragraphs: ['If a duplicate booking is discovered, identify the client commitment and available qualified coverage, contact affected clients promptly and record the agreed change. Investigate whether stale availability, an unexpired hold or a missing travel buffer caused it. Fix that rule rather than relying on people to remember the exception.'] },
    ],
    closing: 'One trusted schedule and a full-interval conflict check protect both the team’s day and the client promise.',
    related: [{ href: '/insights/schedule-multiple-property-photographers', label: 'Plan a multi-photographer day' }, { href: '/real-estate-photography-scheduling-software', label: 'Explore planned scheduling' }],
  },
  {
    slug: 'organize-raw-property-media-files', category: 'Production',
    title: 'How to organize RAW property photos for an editor handoff',
    description: 'Use stable property IDs, service folders, source verification and versioned output locations for real estate photography editing.',
    answer: 'Give every property job a stable identifier, put original source files in a read-only source area, separate services and working versions, and tell the editor exactly which files and outputs are expected. Verify the upload before assigning work and never make the client-facing folder the editor’s working area.',
    intro: 'A folder name alone cannot tell an external editor whether the upload is complete or which files belong in the final package. Structure and an intake check make the handoff actionable.',
    image: '/images/reference/on-site.webp', imageAlt: 'Photographer capturing a property assignment', readingMinutes: 5,
    sections: [
      { heading: 'Choose a stable job-level structure', paragraphs: ['Use a job ID plus recognizable property label without exposing more client information than the team needs. Inside it, separate services, source assets, working versions, submitted finals and approved outputs. Define who may move or replace files, and keep originals intact for later corrections.'], bullets: ['JOB-184/photos/source for originals.', 'JOB-184/photos/submitted/v1 for proposed finals.', 'JOB-184/photos/approved for reviewer-approved exports.', 'Separate video, drone and floor-plan paths when ordered.'] },
      { heading: 'Verify intake before the editor starts', paragraphs: ['The photographer or intake owner checks that the correct property uploaded, expected capture sets are present and files can be opened. Record any missing or corrupt source with an owner and resolution time. A transfer notification is not proof of a complete handoff.'] },
      { heading: 'Send a brief alongside the files', paragraphs: ['For a fictional property, the editor receives job ID, selected source sets, required outputs, style reference, property-specific exceptions and due time. The editor acknowledges the brief and asks about an unclear selection before editing. This example is a suggested operating practice, not an existing PhotoTrackly automation.'] },
      { heading: 'Protect approved versions at delivery', paragraphs: ['The reviewer links approval to the submitted version. A correction enters a new version rather than overwriting the old one. The delivery owner assembles only approved outputs and checks the client-facing package from the recipient view. Apply appropriate access controls to private property and client materials.'] },
    ],
    closing: 'A predictable folder structure works best when it is paired with ownership, completeness checks and approval states.',
    related: [{ href: '/resources/photographer-handoff-template', label: 'Use the handoff template' }, { href: '/insights/track-property-media-revisions-and-versions', label: 'Track corrected versions' }],
  },
  {
    slug: 'delegate-property-media-operations', category: 'Operations',
    title: 'What should a growing property-media owner delegate first?',
    description: 'Prioritize repeatable coordination tasks while keeping client, quality and exception decisions explicitly owned.',
    answer: 'Delegate the repeatable work that interrupts the owner most often and has clear acceptance rules: confirming shoot details, matching files to jobs, assigning standard edits and preparing approved packages. Give the new owner context, authority and escalation triggers. Keep unusual client promises and unresolved quality decisions visible rather than handing them off vaguely.',
    intro: 'Hiring another photographer does not automatically remove the owner’s scheduling, editing and delivery work. The first delegation should address the queue where decisions repeatedly wait.',
    image: '/images/reference/in-studio.webp', imageAlt: 'Property media production team coordinating a job', readingMinutes: 5,
    sections: [
      { heading: 'Audit a week of interruptions', paragraphs: ['Write down what the owner was asked to decide, how often it happened, what information was missing and whether a rule could answer it. Group recurring coordination tasks separately from relationship, scope and quality exceptions. Choose one repeatable queue rather than handing over every responsibility at once.'] },
      { heading: 'Delegate a decision, not just a task', paragraphs: ['For scheduling, specify what a coordinator may confirm and when service or access changes require escalation. For file intake, define completeness before assigning an editor. For delivery, define the approval evidence needed before a package may go to a client. The new owner should update the shared job record when deciding.'], bullets: ['Name the accountable role.', 'Give access to the current brief and history.', 'Specify the acceptance rule and decision deadline.', 'Provide a backup and escalation path.'] },
      { heading: 'Illustrative first handoff', paragraphs: ['A fictional studio owner spends each evening asking editors whether files arrived. A production coordinator takes ownership of source intake: matching property and service folders, flagging gaps to photographers, then assigning complete jobs to editors. The owner receives only exceptions that alter the client promise or require a scope decision. This is an example, not a customer case.'] },
      { heading: 'Check whether delegation actually worked', paragraphs: ['After two weeks, inspect whether the queue moves without private owner messages, whether errors are caught before delivery and which decisions still bounce back. If a rule is unclear, improve it. Do not interpret every escalation as a person failing; it may reveal a missing brief or authority boundary.'] },
    ],
    closing: 'The first delegation should remove a repeatable decision queue while preserving clear responsibility for exceptions.',
    related: [{ href: '/insights/scale-photography-business-without-owner-bottleneck', label: 'Map the owner bottleneck' }, { href: '/insights/property-media-operations-dashboard', label: 'See useful operations signals' }],
  },
];
