import type { Insight } from './insights';

// First publishing batch: distinct questions from the core-authority roadmap.
export const dayOneInsights: Insight[] = [
  {
    slug: 'scale-photography-business-without-owner-bottleneck', category: 'Operations',
    title: 'How to scale a real estate photography business without becoming the bottleneck',
    description: 'Move recurring property-job decisions out of the owner’s inbox with clear roles, handoff rules and a daily exception review.',
    answer: 'Start by listing the decisions only the owner can make. Give routine scheduling, file intake, editing assignment and delivery checks named owners and written acceptance criteria. Keep an exception queue for decisions that genuinely need the owner, then review it at a fixed time.',
    intro: 'More bookings can turn a successful photographer into the person who answers every status question. The goal is to make the next action visible to the team while keeping client commitments and quality decisions accountable.',
    image: '/images/insights/scale-photography-business-without-owner-bottleneck.webp', imageAlt: 'Property media team coordinating production in a studio', readingMinutes: 6,
    sections: [
      { heading: 'Find the decisions that repeatedly wait for you', paragraphs: ['For one week, note each interruption: confirming access, locating files, assigning an editor, approving a revision or checking a delivery. Group requests by decision type, not by the person who asked.', 'Separate exceptions from repeatable work. A client changing the agreed scope may need the owner; checking whether all source folders arrived can use a documented rule.'], bullets: ['Record the trigger and the information needed to decide.', 'Name the role that should normally own the decision.', 'Write what that role may approve and when it must escalate.'] },
      { heading: 'Give each handoff an entry and exit condition', paragraphs: ['A shoot is ready for editing when source sets, job identity and instructions are present. Editing is ready for QC when the expected outputs are submitted. QC is complete only when a reviewer approves or requests a specific change.', 'Put those conditions beside the shared job record. A stage without a next owner still sends the question back to the founder.'] },
      { heading: 'Try the change on one illustrative job', paragraphs: ['Imagine a property order with photos and a floor plan. The coordinator confirms access and assigns the shoot. The photographer uploads both source sets. A production lead checks completeness and assigns the photo editor; the floor plan remains separately tracked. A reviewer approves each output before the coordinator checks the client package.', 'If a source set is missing, the production lead records a blocker and asks the photographer. The owner only receives an escalation if the promised client deadline needs a new decision. This is an operating example, not a customer result.'] },
      { heading: 'Review the system, not every routine update', paragraphs: ['Hold a short daily exception review for unowned, late and blocked jobs. Once a week, inspect which rule caused repeated escalations and improve the brief or handoff. The aim is a team that can answer “who does what next?” from the job record.'], bullets: ['Can each active job show its current owner and due time?', 'Did a handoff wait because an acceptance condition was unclear?', 'Which decisions still require the owner, and why?'] },
    ],
    closing: 'Delegation works when authority, context and escalation are visible together.',
    related: [{ href: '/resources/property-job-status-board-template', label: 'Use the job status board template' }, { href: '/real-estate-photography-workflow-software', label: 'See the planned connected workflow' }],
  },
  {
    slug: 'handle-five-property-shoots-per-day', category: 'Scheduling',
    title: 'How to handle five or more property shoots in a day',
    description: 'Plan a busy property-media day around shoot capacity, service mix, file arrivals, editing, QC and client delivery.',
    answer: 'Plan the whole production day before filling the calendar. For every shoot, account for travel, ordered services, file upload, editing capacity, human review and promised delivery. Assign an owner to each handoff, leave room for exceptions, and check the day’s delivery commitments before accepting more work.',
    intro: 'Five appointments do not represent five identical jobs. A short photo shoot and a photo, video and floor-plan order create different work after the photographer leaves.',
    image: '/images/insights/handle-five-property-shoots-per-day.webp', imageAlt: 'Photographer preparing a property shoot', readingMinutes: 5,
    sections: [
      { heading: 'Build a capacity view from the order, not a fixed slot', paragraphs: ['List address, access window, services, photographer, estimated on-site time, travel and upload needs. Check the downstream queue as well: an available photographer does not mean an editor and reviewer can deliver the work on time.', 'Use local times and the actual service mix. Confirm specialty coverage before promising a slot.'], bullets: ['Who can perform every ordered service?', 'When can the source files arrive?', 'Who has editing and QC capacity before the client deadline?'] },
      { heading: 'Set handoff cutoffs before the first shoot', paragraphs: ['Agree when photographers should flag access failures or scope changes, where each service’s files will land, and when the editor expects a complete brief. If a shoot ends late, the production lead decides whether to reassign or renegotiate the delivery commitment rather than letting the queue silently slip.'] },
      { heading: 'Illustrative day with mixed services', paragraphs: ['Suppose three jobs need photos, one needs photos plus video, and one needs photos plus a floor plan. The coordinator assigns the specialist service first and checks travel between appointments. At midday, a missing access code blocks one job; its owner contacts the site and records the new decision time. At upload, photo sets and the floor-plan source are checked separately.', 'Before sending any package, a reviewer confirms each ordered output. The count of completed appointments alone does not prove the five jobs are ready to deliver.'] },
      { heading: 'Close with an exception sweep', paragraphs: ['At the end of the day, filter for missing uploads, unassigned editing, revisions and due-tomorrow deliveries. Leave a named next owner and a time for each item so the next shift does not reconstruct the day from messages.'], bullets: ['Confirm all shoots have a result: completed, rescheduled or blocked.', 'Match incoming files to the correct property and service.', 'Check tomorrow’s capacity before accepting rush work.'] },
    ],
    closing: 'The daily limit is set by the slowest required handoff, not just open calendar slots.',
    related: [{ href: '/insights/multi-service-shoot-scheduling', label: 'Plan a multi-service shoot' }, { href: '/real-estate-photography-scheduling-software', label: 'Explore planned scheduling' }],
  },
  {
    slug: 'track-every-active-property-media-job', category: 'Operations',
    title: 'How to track every active real estate photography job',
    description: 'Build one reliable active-job view with stage, deliverables, next action, owner, due time and blocker.',
    answer: 'Use one row or record per property job and keep six fields current: stage, ordered deliverables, next action, named owner, due time and blocker. Update the record at each handoff and review exceptions daily. Store service-level progress beneath the job so one finished photo set cannot hide an unfinished video.',
    intro: 'A shared board is useful only if someone can act from it. A list of property addresses and vague “in progress” labels still makes the coordinator ask everyone for status.',
    image: '/images/insights/track-every-active-property-media-job.webp', imageAlt: 'Property interior representing an active media job', readingMinutes: 5,
    sections: [
      { heading: 'Create the minimum job record', paragraphs: ['Give each property order a stable identifier, client, address, committed delivery time and ordered services. Track its broad stage, but pair that stage with the specific next action and owner. A blocker should state what input is missing and who is being asked for it.', 'Record dates with the relevant local time zone, especially when photographers and editors work in different regions.'] },
      { heading: 'Update at the moment responsibility changes', paragraphs: ['When scheduling confirms a shoot, assign the on-site owner. When sources arrive, the receiving production owner checks completeness and assigns editing. When an editor submits finals, a reviewer accepts or requests changes. When all agreed items are approved, a delivery owner verifies the package.'], bullets: ['One person acknowledges each handoff.', 'The previous owner identifies the expected output.', 'A missing input becomes a visible blocker, not an invisible delay.'] },
      { heading: 'Illustrative board entry', paragraphs: ['A fictional job for 14 Harbor Street has photos approved, a video in review and a floor plan awaiting a corrected label. Its overall stage is “review,” next action is “confirm revised floor plan,” owner is the production lead, and the due time is 3 pm local. The service states explain why the job is not ready even though the photos are done.'] },
      { heading: 'Use the board to decide, not merely report', paragraphs: ['Filter jobs due soon, blocked, missing an owner or unchanged past their expected handoff. During the daily review, resolve the next action on those exceptions. Archive delivered jobs only after the recipient and package reference are recorded.'], bullets: ['Can the team identify the next owner without opening a chat?', 'Does every ordered service have a disposition?', 'Is the promised delivery still credible?'] },
    ],
    closing: 'An active-job view is reliable when each handoff changes the record before the next person starts work.',
    related: [{ href: '/resources/property-job-status-board-template', label: 'Copy the status board template' }, { href: '/insights/property-media-job-triage', label: 'Run a daily job triage' }],
  },
  {
    slug: 'property-media-job-statuses', category: 'Operations',
    title: 'What statuses should a property-media job have?',
    description: 'A practical property-job lifecycle that separates scheduling, capture, file intake, editing, review, revisions and delivery.',
    answer: 'Use a small set of job stages such as new, confirmed, scheduled, shot, editing, review, ready and delivered. Add blocked and cancelled as explicit outcomes. Track individual services and revisions separately, because one job can have approved photos and an unfinished floor plan at the same time.',
    intro: 'Statuses should tell the team what decision is next. Too few hide incomplete services; too many force people to debate labels instead of moving work.',
    image: '/images/insights/property-media-job-statuses.webp', imageAlt: 'Property media editor reviewing an active job', readingMinutes: 5,
    sections: [
      { heading: 'Define each stage by its exit condition', paragraphs: ['“New” means the request needs scope and timing confirmation. “Confirmed” means the agreed services are known. “Scheduled” means a responsible photographer has the current brief. “Shot” means capture finished but sources may still be incomplete. “Editing” begins after required sources and instructions are received.', '“Review” starts when proposed finals are submitted; “ready” requires approval of all agreed deliverables and a checked package; “delivered” records the actual recipient and handoff.'] },
      { heading: 'Keep blockers and service states visible', paragraphs: ['A blocked flag should identify missing access, files, client input or an unassigned owner. Do not turn every type of blocker into a new global stage. Give photo, video, drone and floor plan deliverables their own received, in progress, submitted, changes requested or approved states.'], bullets: ['Submitted is not approved.', 'Approved is not delivered.', 'A partial delivery needs an explicit agreement and a record of remaining items.'] },
      { heading: 'Walk a hypothetical mixed order through the states', paragraphs: ['A fictional photo-and-video order moves from scheduled to shot. Photo sources arrive, but the video source is missing, so the job is blocked at intake. After the missing file arrives, both services enter editing. The reviewer approves photos and requests a video title change. The job remains in review until that revision is approved and the client package is checked.'] },
      { heading: 'Test the definitions with the team', paragraphs: ['Ask a coordinator, photographer, editor and delivery owner to name what evidence moves the job to the next stage. If two people disagree, write the acceptance rule next to the status. Avoid changing historical meaning silently when your workflow evolves.'] },
    ],
    closing: 'Good statuses mark accountable decisions while service-level states preserve the detail.',
    related: [{ href: '/resources/property-job-status-board-template', label: 'Use a status board template' }, { href: '/insights/real-estate-media-delivery-readiness', label: 'Define delivery readiness' }],
  },
  {
    slug: 'schedule-multiple-property-photographers', category: 'Scheduling',
    title: 'How to schedule multiple real estate photographers',
    description: 'Schedule a property-media team using availability, services, location, travel, access windows and downstream production capacity.',
    answer: 'Match each property request to a photographer who is available for the entire appointment and travel window and can cover the ordered services. Confirm site access and the client’s time window, then reserve editing and review capacity before promising delivery. Keep one source of truth for changes and notify every affected person.',
    intro: 'An empty calendar slot is only one input. Two jobs can overlap through travel, a specialty service or a late source-file handoff even when their on-site times do not collide.',
    image: '/images/insights/schedule-multiple-property-photographers.webp', imageAlt: 'Residential property awaiting a scheduled media shoot', readingMinutes: 6,
    sections: [
      { heading: 'Collect the constraints for each request', paragraphs: ['Start with property location and access hours, service list, likely shoot duration, client deadline, photographer working windows and travel between jobs. Mark services requiring a specific person or separate appointment. Keep tentative requests distinct from confirmed bookings.'], bullets: ['Who can perform the exact service mix?', 'Is there enough travel and preparation time?', 'Does the assigned person have the current brief?', 'Can production still meet the promised delivery?'] },
      { heading: 'Assign and confirm in one sequence', paragraphs: ['Offer only slots that meet the real constraints. Hold the selected slot while confirming access, then assign the photographer with the full service and contact brief. Ask for acknowledgement; a name on a calendar is not proof the brief was received.', 'When a client reschedules, recheck travel, skills, upload cutoff and editor capacity. Record who accepted the new time.'] },
      { heading: 'Illustrative three-photographer day', paragraphs: ['Suppose two people can capture standard photos and one also handles a specialty service. The specialty order gets checked against that person’s availability first. Two nearby photo jobs can then be assigned with enough travel between them. If access to the first property moves later, the coordinator tests the entire affected sequence before confirming a new time.', 'This is a scheduling example, not a promise that PhotoTrackly automatically optimizes routes.'] },
      { heading: 'Audit tomorrow before leaving today', paragraphs: ['Check unacknowledged assignments, missing access details, tentative holds and service mismatches. A simple exception list is more useful than opening every calendar event.'], bullets: ['Flag any double-booked person or overlapping travel window.', 'Check that every specialist service has an owner.', 'Confirm the client and photographer have the same time zone and address.'] },
    ],
    closing: 'Team scheduling succeeds when a feasible appointment carries the complete property job with it.',
    related: [{ href: '/insights/multi-service-shoot-scheduling', label: 'Check a multi-service shoot brief' }, { href: '/real-estate-photography-scheduling-software', label: 'Explore planned scheduling' }],
  },
  {
    slug: 'manage-multiple-real-estate-photo-editors', category: 'Editing',
    title: 'How to manage multiple real estate photo editors',
    description: 'Assign property editing work with workload visibility, clear briefs, review ownership, revision history and backup coverage.',
    answer: 'Give each property and deliverable a named editor, source-file set, style brief and due time. Track assigned, in progress, submitted, changes requested and approved separately. Review the queue daily for overload or missing inputs, and route revisions back to the correct version and owner.',
    intro: 'Adding editors increases capacity only when everyone can see which property, files and instructions belong to each assignment. A shared folder alone does not show who is responsible for the next decision.',
    image: '/images/insights/manage-multiple-real-estate-photo-editors.webp', imageAlt: 'Editor working on property media in a studio', readingMinutes: 5,
    sections: [
      { heading: 'Assign a complete unit of work', paragraphs: ['Identify the property job, ordered outputs, source location, reference look, special client instructions, expected final format and review deadline. If photos and video have different owners, make that explicit. The receiving editor should acknowledge incomplete or inaccessible files before the clock silently runs.'] },
      { heading: 'Use a queue with meaningful states', paragraphs: ['Show assigned work, active edits, submitted finals and requested changes by editor and deadline. A reviewer is the owner after submission; the editor regains ownership when a specific correction is requested. Record who can cover an absence and what context that person needs.'], bullets: ['Check which assignments have no source files.', 'Check which submissions await review.', 'Check whose deadlines collide with other high-priority jobs.'] },
      { heading: 'Illustrative revision handoff', paragraphs: ['On a fictional property, Editor A submits 20 photos. The reviewer approves 18 and requests corrections to two named images. The change note references the submitted version and expected outcome. Editor A returns a corrected version, and the reviewer approves it before the client package uses it. Other approved files need not be re-reviewed without reason.'] },
      { heading: 'Calibrate quality without rewriting each brief', paragraphs: ['Maintain a short shared style guide and a small set of approved examples. Review repeated corrections together, then update the standard. Keep client-specific exceptions on the job rather than changing the rule for every editor.'], bullets: ['Is the brief actionable without a private message?', 'Can a backup editor find the current files and decision?', 'Does a submitted job have a reviewer and expected response time?'] },
    ],
    closing: 'The system should show both editing capacity and the next accountable handoff.',
    related: [{ href: '/resources/media-editing-review-checklist', label: 'Use the editing review checklist' }, { href: '/real-estate-media-production-management', label: 'Explore planned production tracking' }],
  },
  {
    slug: 'outgrown-spreadsheets-property-media', category: 'Buying guide',
    title: 'Seven signs a property-media team has outgrown spreadsheets',
    description: 'A practical test for when spreadsheet-based job tracking stops giving a property-media team reliable ownership and delivery visibility.',
    answer: 'A spreadsheet is still useful if the team reliably updates it and can act from it. Reconsider the workflow when job status is regularly stale, service details live elsewhere, owners are unclear, revisions lose their versions or delivery requires reconstructing messages. Test those symptoms before buying software.',
    intro: 'The problem is rarely the spreadsheet format itself. It is the gap between a row and the live decisions made across scheduling, capture, editing, QC and delivery.',
    image: '/images/insights/outgrown-spreadsheets-property-media.webp', imageAlt: 'Property photographer working on an assignment', readingMinutes: 5,
    sections: [
      { heading: 'Check seven observable signals', paragraphs: ['Review recent jobs, not a hypothetical feature list. One incident is a reason to improve a process; repeated confusion across roles suggests the current system lacks a reliable handoff.'], bullets: ['People ask the owner for status despite a shared sheet.', 'A calendar change does not update the job brief.', 'One row says complete while another ordered service is unfinished.', 'Files cannot be matched confidently to the property and version.', 'The next action or owner is blank after a handoff.', 'Revision requests live in chat without an approval record.', 'The delivery owner must assemble the package from several places.'] },
      { heading: 'Separate process fixes from tool gaps', paragraphs: ['First add clear field definitions, update rules and one owner per handoff. A small team may get reliable results with a sheet, calendar and folders if it follows those rules. If keeping them synchronized takes more coordination than the work itself, test a connected job workflow.'] },
      { heading: 'Run a one-job comparison', paragraphs: ['Use a fictional property with photos, video and a late reschedule. In your current setup, record how many places must be updated and whether the next person can see the current instructions. Repeat the same journey in a candidate system. Ask the photographer, editor and reviewer to perform their real tasks, not just watch a sales demonstration.'] },
      { heading: 'Decide on the evidence you collected', paragraphs: ['Write the top two failure modes, the cost of changing habits, and what a replacement must demonstrate. Confirm which features exist now and which are planned. PhotoTrackly is in development; early access is a way to register interest, not an available replacement today.'] },
    ],
    closing: 'The trigger to change systems is recurring lost context, not a particular number of rows.',
    related: [{ href: '/insights/evaluate-property-media-workflow-software', label: 'Use a one-job software evaluation' }, { href: '/real-estate-photography-business-software', label: 'See PhotoTrackly’s planned scope' }],
  },
  {
    slug: 'real-estate-photography-editing-workflow', category: 'Editing',
    title: 'How to build a real estate photography editing workflow',
    description: 'Define the path from source-file intake to editor assignment, submitted finals, human review, revisions and approval.',
    answer: 'Treat editing as a sequence of accountable handoffs: confirm the source files and brief, assign an editor and due time, receive a versioned submission, review against the order, request exact corrections if needed, and approve the final files. Do not treat an upload as approval.',
    intro: 'Editing workflow design matters when more than one person can touch a job. Clear inputs and exit criteria keep a missing image or an ambiguous revision from becoming a client-facing problem.',
    image: '/images/insights/real-estate-photography-editing-workflow.webp', imageAlt: 'Property media editor at work', readingMinutes: 5,
    sections: [
      { heading: 'Make intake a real checkpoint', paragraphs: ['The intake owner matches the property and service list to uploaded source folders. Confirm expected image sets, any video or floor-plan material, and property-specific instructions. Flag missing files with a named person to resolve them before marking the job ready for editing.'] },
      { heading: 'Give the editor an actionable assignment', paragraphs: ['The brief should include the current source location, style reference, requested outputs, delivery format and due time. Keep general standards in a reusable guide and exceptions on the property job. Set a response path for questions so the editor does not guess.'], bullets: ['Assigned: editor acknowledges a complete brief.', 'In progress: production work is underway.', 'Submitted: proposed finals are ready for review.', 'Changes requested or approved: a reviewer makes the decision.'] },
      { heading: 'Use versions for revisions', paragraphs: ['In a hypothetical job, an editor submits a first set and the reviewer notices a missing exterior and incorrect color on two interiors. The reviewer names the affected files and desired changes, then assigns the revision back to the editor. The corrected set receives a new version; the reviewer records acceptance of that version only.'] },
      { heading: 'Connect approval to the wider job', paragraphs: ['A photo set can be approved while a floor plan remains in review. The delivery owner checks all ordered services, the approved version and the client-facing package before sending. Review recurring errors with the team and update the handoff rule rather than adding more vague status labels.'] },
    ],
    closing: 'An editing workflow ends at documented approval, then hands off to a separate delivery decision.',
    related: [{ href: '/resources/media-editing-review-checklist', label: 'Use the editing and review checklist' }, { href: '/real-estate-media-production-management', label: 'Explore planned production management' }],
  },
  {
    slug: 'track-property-media-revisions-and-versions', category: 'Quality review',
    title: 'How to track property-media revisions without losing versions',
    description: 'Keep review requests, affected files, editor ownership and approval linked to the correct version of a property job.',
    answer: 'Attach each revision request to the specific deliverable and submitted version. Record the issue, expected correction, requester, editor owner and due time. When a corrected version arrives, review that version and mark exactly which files are approved; keep superseded files out of the client package.',
    intro: 'A message saying “please fix the photos” is hard to execute and harder to audit. Revisions need a reference point so the editor and reviewer are looking at the same files.',
    image: '/images/insights/track-property-media-revisions-and-versions.webp', imageAlt: 'Interior property image representing a media review', readingMinutes: 5,
    sections: [
      { heading: 'Name the version and affected deliverable', paragraphs: ['Use a stable property identifier and a submission version. For each issue, identify the image or video segment, what is wrong, what the acceptable result looks like and who will decide when it is fixed. Keep general client feedback separate from a change to the agreed scope.'] },
      { heading: 'Route the decision back to the right person', paragraphs: ['The reviewer requests changes, the production owner assigns a responsible editor, and the editor submits a new version. The reviewer either approves it or requests another precise correction. If a client asks for a different deliverable, the coordinator first confirms scope and timing.'], bullets: ['Request only the changes needed on the affected files.', 'Preserve the original and corrected versions until approval is clear.', 'Record the reviewer’s acceptance before changing the service to approved.'] },
      { heading: 'Illustrative revision history', paragraphs: ['For a fictional address, v1 has 24 images. The reviewer requests a vertical correction on image 07 and an exterior replacement for image 21. The editor submits v2 with those two items and the reviewer approves them. The delivery package contains 22 unchanged approved files plus the two approved v2 replacements, not both old and new copies.'] },
      { heading: 'Check the final package from the recipient view', paragraphs: ['Verify the correct property, approved files, naming and access. If some services are intentionally sent later, record the client agreement and the outstanding items. A completed revision task is not by itself a complete property-job delivery.'] },
    ],
    closing: 'Version lineage makes approval and delivery decisions explainable after the chat has moved on.',
    related: [{ href: '/insights/real-estate-media-delivery-readiness', label: 'Check delivery readiness' }, { href: '/resources/media-editing-review-checklist', label: 'Use a review checklist' }],
  },
  {
    slug: 'organize-photo-video-drone-floor-plan-one-property', category: 'Production',
    title: 'How to organize photo, video, drone and floor plan for one property',
    description: 'Keep multi-service property media files under one job while tracking each deliverable’s owner, version and approval independently.',
    answer: 'Create one property job with a stable identifier and a separate deliverable entry for each ordered service. Use predictable folders and file names, assign an owner and expected output to each service, and record review and approval per deliverable. The whole job is ready only when the agreed package is checked.',
    intro: 'A mixed-media order is easy to fragment into unrelated folders and conversations. One shared job record connects the client commitment while service-level states preserve the detail.',
    image: '/images/insights/organize-photo-video-drone-floor-plan-one-property.webp', imageAlt: 'Property exterior representing a multi-service media order', readingMinutes: 5,
    sections: [
      { heading: 'Start with the order and a stable job identifier', paragraphs: ['Record client, property, requested date and exactly which outputs were ordered. Do not assume “media package” explains the number, format or handling of every item. If an add-on arrives later, note who approved it and its effect on delivery timing.'] },
      { heading: 'Give each service its own path', paragraphs: ['Use a consistent structure such as job identifier / service / source, working and approved. Define who uploads and who reviews each service. Keep source materials distinct from client-ready files and do not overwrite an approved version with a new draft.'], bullets: ['Photos: source set, selected finals and approval.', 'Video: source clips, edit versions and final format.', 'Drone: source and final assets with the responsible operator.', 'Floor plan: source notes, draft, corrected and approved output.'] },
      { heading: 'Illustrative package assembly', paragraphs: ['A fictional order includes photos, video, drone images and a floor plan. The photographer uploads photo and drone source sets; a video editor receives clips; a floor-plan specialist returns a draft. The reviewer approves photos and drone, requests a floor-plan label correction, and awaits the video export. The delivery owner sees these as four dispositions under one property job.'] },
      { heading: 'Perform a cross-service delivery check', paragraphs: ['Match the approved items back to the original service list. Open the package as the client, verify property identity and access, and record any agreed partial delivery. A shared folder name does not prove all promised services are present.'] },
    ],
    closing: 'One job holds the client promise; service-level ownership and approval make the promise checkable.',
    related: [{ href: '/insights/real-estate-media-delivery-readiness', label: 'Check when the job is ready' }, { href: '/resources/shoot-to-delivery-checklist', label: 'Use the shoot-to-delivery checklist' }],
  },
];
